Feature/4 UI create room flow
dnd-side-project/dnd-10th-10-iOS pull request #15
Opened 2024-02-17 11:12 UTC by sunny5875

## What is this PR? 🔍 

- 방 생성하는 부분의 UI가 많이.. 바뀌어서 해당 부분을 반영하면서 방생성 flow UI 를 완료했습니다.

## Changes 📝
- 다만, 시뮬레이터로 보니 키보드 확인에 제한이 있어 제대로 모두 확인하지는 못했습니다 ㅠ 
- roomViewModel이름을 createRoomViewModel로 바꾸었습니다! roomViewModel 하나로 쓰기에는 방생성, 방 입장하기, 방기다리기, 방내부 등등 역할이 많은 것 같아 해당 뷰모델은 createRoomViewModel로 두고 나머지 플로우에 대한 뷰모델을 각자 생성하는 게 좋을 것 같습니다 확인부탁드려요 :)
- 캘린더 기간 몇일까지로 할건지 나와있지 않아서 그냥 60일까지로 해놨어요 그리고 레이블도 혼재되어있어서 스샷에 나온대로 했는데 한번 얘기해보면 좋을 것 같습니다!

## Screenshot 📷

<img src="https://github.com/dnd-side-project/dnd-10th-10-iOS/assets/55349553/54c8ab85-56ce-4452-92ce-39ebadef15b8" width="30%" height="30%"/>
<img src="https://github.com/dnd-side-project/dnd-10th-10-iOS/assets/55349553/881a5c4a-5a1e-4054-ab7b-06c45f415d2a" width="30%" height="30%"/>
<img src="https://github.com/dnd-side-project/dnd-10th-10-iOS/assets/55349553/b51f3def-da8b-4ea0-9a54-4231e217f944" width="30%" height="30%"/>
<img src="https://github.com/dnd-side-project/dnd-10th-10-iOS/assets/55349553/952bc3f4-ddc9-4f65-abed-8bf0e815b91f" width="30%" height="30%"/>

## 관련 이슈

- Resolved: #4

2024-02-17 17:06 UTC, jane1choi requested changes
컴포넌트들 UI 수정사항 때문에,, 다시 작업하기 번거로우셨을텐데 수고하셨습니다🥹👏
불필요한 import 문 삭제해주시면 좋을 것 같고, `ViewModelable` 관련해서 제안드린 것 있는데 한번 확인해주시면 감사하겠습니다!!
코디네이터는 저도 고민중인 부분이라.. 현상태 유지하고 좀 더 고민해서 리팩토링 하는 것도 좋을 것 같아요~! 관련해서 고민되는 사항도 코멘트로 남겨두었으니 확인해주시면 감사하겠습니다!!!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Coordinator/BaseCoordinator.swift
> +    }
p1;
`path.removeAll()` 로 수정하는건 어떨까요??

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Coordinator/BaseCoordinator.swift
> +    }
p1;
해당 코드는 왜 필요한지 궁금합니다!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Coordinator/BaseCoordinator.swift
> +import Foundation
p1;
불필요한 임포트 삭제해주시면 좋을 것 같습니다!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/Date+.swift
> +    /// timestamp를 날짜로 변경하는 메소드
p1;
주석에 연산프로퍼티로 설명 변경해주시면 좋을 것 같습니다!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/String+.swift
> +    }
p1;
해당 프로퍼티가 필요한 이유는 무엇인가요?
`isEmpty` 프로퍼티만으로 충분할 것 같습니다.

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/String+.swift
> +import Foundation
p1;
SwiftUI 프레임워크 내 임포트되어있으므로 불필요한 임포트 삭제해주시면 좋을 것 같습니다!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/UIApplication+.swift
> +import Foundation
p1;
불필요한 임포트 삭제 부탁드립니다.

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Interface/Redueable.swift
> +}
p1;
해당 프로토콜 삭제하고 `ViewModelable` 프로토콜을 아래와 같이 구성하는 것 어떨지 제안드립니다!!
Rx-MVVM에서의 Input-Output 구조와 비슷한 방법으로 생각해주시면 좋을 것 같아요!! (Input: Action, Output: State)

```Swift
protocol ViewModelable: ObservableObject {
  associatedtype Action
  associatedtype State
  
  var state: State { get }
  
  func action(_ action: Action)
}
```
참고 자료: https://ios-development.tistory.com/1128

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Presentation/Home/ViewModel/HomeVIewModel.swift
>  }
p1;
파일이름 오타 HomeViewModel 로 수정해주시면 좋을 것 같습니다!

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Presentation/Room/Coordinator/RoomCoordinator.swift
> +enum RoomCoordinatorAction: Hashable {
p1;
요거 네이밍 ~Action 보다 '경로' 임을 명시해줄 수 있도록 ~Path 혹은 ~Flow 이런 식으로 수정해주는 건 어떨까요?

2024-02-17 17:06 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/RoomView.swift
> +        NavigationStack(path: $coordinator.path) {
흠...view가 코디네이터에 대한 정보를 모르도록하고, 뷰모델-코디네이터 간 의존성, 뷰-뷰모델 간 의존성을 갖도록 설계한 다음
뷰모델에게 화면전환을 요청하면 뷰모델이 코디네이터에게 다시 화면전환을 요청해 화면전환이 이루어지도록 하는 것이 좋은 설계라고 생각하는데,, 
SwiftUI에서 요 NavigationStack 이 View에 위치하다보니.. 이렇게 설계하기가 어렵더라구요...
View와 코디네이터에 대한 의존성을 끊어낼 수 있는 방법을 더 고민해보면 좋을 것 같아요..!! 저도 고민 좀 더 해보겠습니다!

2024-02-18 02:21 UTC, sunny5875 commented on Basterdz-iOS/Basterdz-iOS/Util/Coordinator/BaseCoordinator.swift
> +    }
코디네이터에 필수로 구현해야하는 함수여서 추가했습니다 navigationDestination에서 불러야하는 함수라고 생각하시면 될 것 같아욥!

2024-02-18 02:24 UTC, sunny5875 commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/String+.swift
> +    }
비어있지 않을 때 ui가 바뀌어야하는 경우가 많은데 그럴 때마다 !()를 쓰는게 번거롭고 코드를 읽기 쉽게 하기 위함입니다
저는 이 프로퍼티가 있어서 코드 읽기가 훨씬 수월해져서 웬만하면 유지하고 싶습니다!

2024-02-18 02:26 UTC, sunny5875 commented on Basterdz-iOS/Basterdz-iOS/Presentation/Room/Coordinator/RoomCoordinator.swift
> +enum RoomCoordinatorAction: Hashable {
안그래도 좀 고민했었는뎅 좋습니다!path로 수정하겠습니다

2024-02-18 02:28 UTC, sunny5875 commented on Basterdz-iOS/Basterdz-iOS/Presentation/Room/View/RoomView.swift
> +        NavigationStack(path: $coordinator.path) {
저도 같은 부분에서 고민하고 있습니다 ㅠㅠ 
뷰가 코디네이터를 모르는 게 좋겠지만 어쩔 수 없이 뷰에 코드가 있다보니 어쩔 수 없이 roomView에서는 뷰와 코디네이터 간의 연결이 되어있는 상태로 우선은 구현했습니다 ㅠㅠ
함께 더 좋은 자료 찾아봐용!! 저도 찾아보겠습니다

2024-02-18 02:30 UTC, sunny5875 commented on Basterdz-iOS/Basterdz-iOS/Util/Interface/Redueable.swift
> +}
약간 TCA같이 생겼군요 좀 더 state 관리가 쉬워질 것 같아 좋을 것 같습니다! 반영해보겠습니다

2024-02-18 04:27 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Extension/String+.swift
> +    }
@sunny5875 
저는 개인적으로 ! 를 붙이는게 더 명시적이라고 생각하긴 합니다만,, 유지하고 싶으시다면 두어도 괜찮을 것 같습니다..!

2024-02-18 04:34 UTC, jane1choi approved these changes
수정사항 다 확인했습니다!! 뷰모델 관련도 다 수정하기 번거로우셨을텐데 고생 많으셨어요!!
코디네이터 path 관련 추가 코멘트만 한번 확인 부탁드립니다!!!

2024-02-18 04:34 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Presentation/Room/Coordinator/RoomCoordinator.swift
> +    @ViewBuilder func setView(_ action: RoomCoordinatorFlow) -> some View {
p2;
`RoomFlow` 이렇게 사용하는 건 어떻게 생각하세요~? 
path를 나타내는 enum 네이밍에 굳이 Coordinator가 들어가지 않아도 될 것 같다는 생각이 들어 제안합니다!

2024-02-18 04:34 UTC, jane1choi commented on Basterdz-iOS/Basterdz-iOS/Util/Interface/ViewModelable.swift
>  }
👍🏻👍🏻👍🏻

2024-02-18 04:39 UTC, merged